version: '3'

services:
  gobooks-backend:
    build: .
    image: gobooks-backend:latest
    container_name: gobooks-backend
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - /srv/upload-files:/srv/upload-files