spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796020689593-3eujab8a22ippd49mt2g6knf3gue3f10.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "https://www.gobookstore.shop/login/oauth2/code/google"

          naver:
            client-id: rEYXDiOq3pN6eTmXTZuc
            client-secret: YrNsXsi8jq
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.gobookstore.shop/login/oauth2/code/naver"

          kakao:
            client-id: 356b408a7841ab8d67a96773594a023e
            client-secret: 3DHYsMiWUcnLG6xCBiyFjrEN5nFZuOC0
            scope: profile, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.gobookstore.shop/login/oauth2/code/kakao"

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id