spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796020689593-3eujab8a22ippd49mt2g6knf3gue3f10.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

          naver:
            client-id: rEYXDiOq3pN6eTmXTZuc
            client-secret: YrNsXsi8jq
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response